AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-xxxxxxxx
      KeyName: my-key
      SecurityGroups: [default]
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-demo-bucket
